// flow-typed signature: 6ee39a46400ef089187eeb8d4f904c46
// flow-typed version: <<STUB>>/styled-components-modifiers_v^1.0.1/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-components-modifiers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-components-modifiers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'styled-components-modifiers/dist/applyResponsiveStyleModifiers' {
  declare module.exports: any;
}

declare module 'styled-components-modifiers/dist/applyStyleModifiers' {
  declare module.exports: any;
}

declare module 'styled-components-modifiers/dist/index' {
  declare module.exports: any;
}

declare module 'styled-components-modifiers/dist/responsiveStyleModifierPropTypes' {
  declare module.exports: any;
}

declare module 'styled-components-modifiers/dist/styleModifierPropTypes' {
  declare module.exports: any;
}

declare module 'styled-components-modifiers/dist/utils/modifiedStyles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'styled-components-modifiers/dist/applyResponsiveStyleModifiers.js' {
  declare module.exports: $Exports<'styled-components-modifiers/dist/applyResponsiveStyleModifiers'>;
}
declare module 'styled-components-modifiers/dist/applyStyleModifiers.js' {
  declare module.exports: $Exports<'styled-components-modifiers/dist/applyStyleModifiers'>;
}
declare module 'styled-components-modifiers/dist/index.js' {
  declare module.exports: $Exports<'styled-components-modifiers/dist/index'>;
}
declare module 'styled-components-modifiers/dist/responsiveStyleModifierPropTypes.js' {
  declare module.exports: $Exports<'styled-components-modifiers/dist/responsiveStyleModifierPropTypes'>;
}
declare module 'styled-components-modifiers/dist/styleModifierPropTypes.js' {
  declare module.exports: $Exports<'styled-components-modifiers/dist/styleModifierPropTypes'>;
}
declare module 'styled-components-modifiers/dist/utils/modifiedStyles.js' {
  declare module.exports: $Exports<'styled-components-modifiers/dist/utils/modifiedStyles'>;
}
